#!/usr/bin/env python3
"""
Generate README.md AND web/data/entries.js from entries.json.
Run: python3 scripts/build.py

entries.json is the single source of truth.
Both README.md and web/data/entries.js are generated artifacts — never edit them by hand.
"""

import json
from pathlib import Path

ROOT = Path(__file__).parent.parent
ENTRIES_FILE = ROOT / "entries.json"
README_FILE = ROOT / "README.md"
WEB_DATA_FILE = ROOT / "web" / "data" / "entries.js"

CATEGORY_EMOJI = {
    "Tool": "🔧",
    "Language": "💻",
    "Platform": "☁️",
    "Framework": "🏗️",
    "Concept": "💡",
    "Other": "📌",
}

DOMAIN_EMOJI = {
    "Networking": "🌐",
    "DevOps": "⚙️",
    "Cloud": "☁️",
    "Database": "🗄️",
    "AI/ML": "🤖",
    "SRE/Observability": "📡",
    "Security": "🔒",
    "Data Engineering": "🔀",
    "Frontend": "🖥️",
    "Backend": "🔌",
    "Messaging": "📨",
    "Storage": "💾",
    "CI/CD": "🚀",
    "Identity": "🪪",
    "Other": "📌",
}

# Preferred display order for domains
DOMAIN_ORDER = [
    "Networking", "DevOps", "Cloud", "Database", "AI/ML",
    "SRE/Observability", "Security", "Data Engineering",
    "Frontend", "Backend", "Messaging", "Storage", "CI/CD", "Identity", "Other",
]


def domain_sort_key(d):
    try:
        return DOMAIN_ORDER.index(d)
    except ValueError:
        return len(DOMAIN_ORDER)


def load_entries():
    """Load + sort entries, then assign stable 'dex' numbers in display order."""
    entries = json.loads(ENTRIES_FILE.read_text())
    entries.sort(key=lambda e: (domain_sort_key(e.get("domain", "Other")), e["name"].lower()))
    for i, e in enumerate(entries):
        e["dex"] = i + 1
    return entries


def build_readme(entries):
    domains = sorted(set(e.get("domain", "Other") for e in entries), key=domain_sort_key)
    categories = sorted(set(e["category"] for e in entries))
    total = len(entries)

    lines = []

    # Header
    lines += [
        "# ⚡ TechDex",
        "",
        "",
        "---",
        "",
        "## 📊 Stats",
        "",
        f"| Total Entries | Domains | Categories | With Docs | With Tutorials |",
        f"|:---:|:---:|:---:|:---:|:---:|",
        f"| {total} | {len(domains)} | {len(categories)} | {sum(1 for e in entries if e.get('docs'))} | {sum(1 for e in entries if e.get('tutorial'))} |",
        "",
        "---",
        "",
        "## 📑 Table of Contents",
        "",
    ]

    # TOC by domain
    for domain in domains:
        emoji = DOMAIN_EMOJI.get(domain, "📌")
        anchor = domain.lower().replace("/", "").replace(" ", "-")
        lines.append(f"- [{emoji} {domain}](#{anchor})")
    lines += ["", "---", ""]

    # Entries by domain
    for domain in domains:
        emoji = DOMAIN_EMOJI.get(domain, "📌")
        anchor = domain.lower().replace("/", "").replace(" ", "-")
        domain_entries = [e for e in entries if e.get("domain", "Other") == domain]
        lines += [
            f"## {emoji} {domain}",
            "",
            "| Name | ELI5 | Description | Use Cases | Used By | Docs | Tutorial |",
            "|------|------|-------------|-----------|---------|------|----------|",
        ]
        for e in domain_entries:
            name = e["name"]
            eli5 = e.get("eli5", "")
            # Collapsible description
            desc_full = e["description"].replace("|", "\\|")
            desc_preview = desc_full[:60] + "…" if len(desc_full) > 60 else desc_full
            desc = f"<details><summary>{desc_preview}</summary>{desc_full}</details>"
            # Collapsible use cases
            uc_list = e.get("use_cases", [])
            if uc_list:
                uc_items = "".join(f"<li>{u}</li>" for u in uc_list)
                use_cases = f"<details><summary>{len(uc_list)} use cases</summary><ul>{uc_items}</ul></details>"
            else:
                use_cases = "—"
            used_by = ", ".join(e.get("used_by", []))
            docs = f"[Docs]({e['docs']})" if e.get("docs") else "—"
            tutorial = f"[Tutorial]({e['tutorial']})" if e.get("tutorial") else "—"
            lines.append(f"| **{name}** | {eli5} | {desc} | {use_cases} | {used_by} | {docs} | {tutorial} |")
        lines += ["", ""]

    # Footer
    lines += [
        "---",
        "",
        f"*Last updated: {__import__('datetime').date.today()} · Auto-generated by `scripts/build.py`*",
    ]

    README_FILE.write_text("\n".join(lines))


def build_web_data(entries):
    """Emit web/data/entries.js — consumed by the browsable site in web/.

    Generated artifact: the site reads window.TECHDEX_ENTRIES from this file.
    Do not edit by hand; re-run this script after changing entries.json.
    """
    WEB_DATA_FILE.parent.mkdir(parents=True, exist_ok=True)
    payload = json.dumps(entries, ensure_ascii=False, indent=1)
    WEB_DATA_FILE.write_text(
        "// Auto-generated from entries.json by scripts/build.py — do not edit.\n"
        "window.TECHDEX_ENTRIES = " + payload + ";\n"
    )


def build():
    entries = load_entries()
    domains = sorted(set(e.get("domain", "Other") for e in entries), key=domain_sort_key)
    categories = sorted(set(e["category"] for e in entries))
    total = len(entries)

    build_readme(entries)
    build_web_data(entries)

    print(
        f"✅ Generated README.md + web/data/entries.js — "
        f"{total} entr{'y' if total == 1 else 'ies'} across {len(domains)} "
        f"domain{'s' if len(domains) != 1 else ''}, {len(categories)} "
        f"categor{'y' if len(categories) == 1 else 'ies'}."
    )


if __name__ == "__main__":
    build()
