#!/usr/bin/env python3
"""
Generate README.md from entries.json.
Run: python3 scripts/build.py
"""

import json
from pathlib import Path

ROOT = Path(__file__).parent.parent
ENTRIES_FILE = ROOT / "entries.json"
README_FILE = ROOT / "README.md"

CATEGORY_EMOJI = {
    "Tool": "🔧",
    "Language": "💻",
    "Platform": "☁️",
    "Framework": "🏗️",
    "Concept": "💡",
    "Other": "📌",
}

def build():
    entries = json.loads(ENTRIES_FILE.read_text())
    entries.sort(key=lambda e: (e["category"], e["name"].lower()))

    categories = sorted(set(e["category"] for e in entries))
    total = len(entries)

    lines = []

    # Header
    lines += [
        "# ⚡ TechDex",
        "",
        "Personal Pokédex for tools, technologies, frameworks and concepts — encountered, logged, and ready to reference.",
        "Entries managed via `entries.json` · README auto-generated by `scripts/build.py` · Repo: [hack-monk/techdex](https://github.com/hack-monk/techdex)",
        "",
        "---",
        "",
        "## 📊 Stats",
        "",
        f"| Total Entries | Categories | With Docs | With Tutorials |",
        f"|:---:|:---:|:---:|:---:|",
        f"| {total} | {len(categories)} | {sum(1 for e in entries if e.get('docs'))} | {sum(1 for e in entries if e.get('tutorial'))} |",
        "",
        "---",
        "",
        "## 📑 Table of Contents",
        "",
    ]

    # TOC
    for cat in categories:
        emoji = CATEGORY_EMOJI.get(cat, "📌")
        anchor = cat.lower().replace(" ", "-")
        lines.append(f"- [{emoji} {cat}](#{anchor}s)")
    lines += ["", "---", ""]

    # Entries by category
    for cat in categories:
        emoji = CATEGORY_EMOJI.get(cat, "📌")
        cat_entries = [e for e in entries if e["category"] == cat]
        lines += [
            f"## {emoji} {cat}s",
            "",
            "| Name | Description | Use Cases | Used By | Docs | Tutorial |",
            "|------|-------------|-----------|---------|------|----------|",
        ]
        for e in cat_entries:
            name = e["name"]
            desc = e["description"].replace("|", "\\|")
            # truncate description for table readability
            if len(desc) > 120:
                desc = desc[:117] + "..."
            use_cases = "<br>".join(f"• {u}" for u in e.get("use_cases", []))
            used_by = ", ".join(e.get("used_by", []))
            docs = f"[Docs]({e['docs']})" if e.get("docs") else "—"
            tutorial = f"[Tutorial]({e['tutorial']})" if e.get("tutorial") else "—"
            lines.append(f"| **{name}** | {desc} | {use_cases} | {used_by} | {docs} | {tutorial} |")
        lines += ["", ""]

    # Footer
    lines += [
        "---",
        "",
        f"*Last updated: {__import__('datetime').date.today()} · Auto-generated by `scripts/build.py`*",
    ]

    README_FILE.write_text("\n".join(lines))
    print(f"✅ README.md generated — {total} entr{'y' if total == 1 else 'ies'} across {len(categories)} categor{'y' if len(categories) == 1 else 'ies'}.")

if __name__ == "__main__":
    build()
